### ISSUE TITLE
Plates Usage Dashboard

### ISSUE THREAD

**Issue by mdse63** [bodhish/plate-printing#22]
Dashboard view

[Plates] - [TODAY]           [Total Jobs] - [TODAY]          [Wasted] - [TODAY]
[plates this month]           [total jobs this month]           [total waste this month]

Display this without using up much space on the screen.

**Comment by ajaleelp** [comment]
What exactly is the concern here? Required data not being present or
styling improvement ? :)

**Comment by mdse63** [comment]
Required data not present.

**Comment by mdse63** [comment]
> Required data not present.

In the excel I can see 
Total Plates for the day
Total plates this month
Total jobs per day &
Wastes per day

**Comment by ajaleelp** [comment]
This is done. Design revamp left.
