### ISSUE TITLE
New Feature - Login for Guests

### ISSUE THREAD

**Issue by mdse63** [bodhish/plate-printing#33]
We may have temporary or part time drivers for the delivery part. They won't have company email accounts, but I'd like them to access the delivery part of it and just click on Delivered and set their name to it. To track time, person who delivered it etc.

**Comment by ajaleelp** [comment]
Login with password is now live. Need to further discuss access control requirements.

**Comment by ajaleelp** [comment]
Seems stale. File new issue if still a requirement.
