### ISSUE TITLE
New Feature - Extended Dashboard

### ISSUE THREAD

**Issue by mdse63** [bodhish/plate-printing#38]
Extended dashboard which can be accessed by clicking somewhere that takes you to a separate window with much more information. Such as:
1. Targets and its statuses 
2. Plate usages - different sizes and customers
3. Plates wasted - size wasted and for which job

**Comment by ajaleelp** [comment]
@mdse63 Do you have a sample layout of what all you would like to be seen on this page and how?

**Comment by bodhish** [comment]
Completed in 451ce1d
