### ISSUE TITLE
New Feature - Set Targets

### ISSUE THREAD

**Issue by mdse63** [bodhish/plate-printing#40]
Set targets weekly and monthly on the admin panel and users can see the targets (through the extended dashboard).

**Comment by ajaleelp** [comment]
@mdse63 Are these targets for individual users or the entire company?

**Comment by mdse63** [comment]
For the entire company.

**Comment by ajaleelp** [comment]
@mdse63 Also, are these targets for total jobs to be done or total plates to be used?

**Comment by mdse63** [comment]
Total plates

**Comment by ajaleelp** [comment]
Done in de994ad

**Comment by ajaleelp** [comment]
Re-opening as I missed out on monthly targets. 
@mdse63 Is monthly target a different metric or the sum of all weekly targets? If it's the sum of all weekly targets, we need to discuss how we account for weeks which are partially inside the month.

**Comment by ajaleelp** [comment]
Closing as no response. Reopen or re-file if still relevant.
