### ISSUE TITLE
Create cashbook (P2)

### ISSUE THREAD

**Issue by ajaleelp** [bodhish/plate-printing#52]
Add a `CashBookEntry` model with date, particular (string), category (enum) and amount (float, can be negative for debits). Provide index, edit pages to create and view them. 

- [x] create a `CashBookEntry` model with columns (date, particular, category, amount)
- [x] Add and in index page to list cash book entries
- [x] Add create and edit pages
- [x] Add option to search by category and date
- [ ] paginate as required

**Comment by bodhish** [comment]
@mdse63 skipping pagination for now
